CloudSixteen/Clockwork

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_plugin.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua
Because Kuro had to make his commit into the master.
> Merging master into test

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_bitflags.lua
> Bitflag library loop efficiencies

- Clockwork/garrysmod/gamemodes/clockwork/gamemode/external/utf8.lua
Now works in conjunction with GMod's utf8 library. This wasn't used anywhere in the codebase other than this file, seemingly.
> Attach Clockwork UTF-8 library to utf8 module

- Clockwork/garrysmod/gamemodes/clockwork/plugins/salesmen/plugin/entities/entities/cw_salesman/init.lua
Checks if salesman custom dialogue is empty. If it is then it prevents the display of the message.
Ex. ' (Name) says "" '
> Salesman check if dialogue is empty.

- Clockwork/garrysmod/gamemodes/clockwork/framework/entities/weapons/cw_hands/shared.lua
Generally cleaned up the code too, making the angles -90 simply fixes the issue without screwing the deploy animation so
> Fixed deploy sequence with the fists

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/areadisplays/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/cleanedmaps/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/crossserverchat/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/delaylooc/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/doorcommands/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/dynamicadverts/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/emoteanims/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/mapscene/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/observermode/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/pickupobjects/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/reportplayer/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/salesmen/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/spawnpoints/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/spawnsaver/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/stamina/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/staticents/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/storage/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/surfacetexts/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/thirdperson/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/toolguns/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/weaponselect/plugin/language/sh_korean.lua
> Create sh_korean.lua file.

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
> update korean language file.

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
I forgot to rename the table...
Anyway, Update more strings!
> Update korean translation / Wrong translation table fixed.

- Clockwork/garrysmod/gamemodes/clockwork/plugins/displaytyping/plugin/language/sh_korean.lua
> Add Korean translation.

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/areadisplays/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/cleanedmaps/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/crossserverchat/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/delaylooc/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/doorcommands/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/spawnpoints/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/spawnsaver/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/stamina/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/staticents/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/weaponselect/plugin/language/sh_spanish.lua
Corrected some mistakes
Translated new CW strings
> Spanish Language Update

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/salesmen/plugin/language/sh_korean.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/weaponselect/plugin/language/sh_korean.lua
> Update Korean language translation.

- Clockwork/garrysmod/gamemodes/clockwork/framework/config/cl_config.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/config/sv_config.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/derma/cl_character.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_english.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_spanish.lua
Added a config for character name limits between 1 character and 128 characters and just added the actual limit
> Character Name Limit

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
Add missing languages, fixed wrong texts.
> Update korean translation.

- Clockwork/garrysmod/gamemodes/clockwork/framework/derma/cl_business.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/derma/cl_storage.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_english.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/spawnpoints/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/staticents/plugin/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/plugins/weaponselect/plugin/language/sh_spanish.lua
Updated Spanish Translation
Fixed Business InfoText not displaying the language string
Added Language Support for "Transfer" button at storage derma
> Added Language Support for "Transfer" button & Updated Spanish Translation

- Clockwork/garrysmod/gamemodes/clockwork/framework/commands/sh_plysetflags.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_spanish.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/system/sh_manage_config.lua
Fixed PlySetFlags output text
Fixed System - Manage Config NumSlider "Value" to support languages
> Fixes PlySetFlags - Add an string to language support

- Clockwork/garrysmod/gamemodes/clockwork/framework/commands/sh_plyrespawntp.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_english.lua
- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_spanish.lua
Fixed PlyRespawnTp (trace.endpos should be trace.HitPos)
Updated Spanish Language
Removed repeated string in English Language
> Fixed PlyRespawnTp & Updated Spanish Translation

- Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua
- Clockwork/garrysmod/gamemodes/cwexample/schema/sv_schema.lua
oh god i don't know how git pull requests work why did my new commit get taken onto the same pull request aaaaaaaaaa
> Fix 'prop spawning' translation string, add Example Functions to Example Schema

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_crafting.lua
Fixed 'The CraftBlueprint command has failed to run' error.
> Crafting FIx

- Clockwork/garrysmod/gamemodes/clockwork/framework/cl_theme.lua
> Gradient nil bug fix.

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_crafting.lua
Fixes #333.
Thanks Vizurez and TacticalToaster for the help!
> Fixed CheckTakeItems from taking the same unique item multiple times. Fixes #333.

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_player.lua
Fixes issue where some Whitelists were lost after UnWhitelisting someone (Only happens on Linux systems)
> Fixes issue where some Whitelists were lost

- Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
> Fix wrong language format.

- Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua
Corrected the single quotations surrounding data in the modified sharedvars message.
> Update sharedvars message

- Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua
Changed content pack to that uploaded by Robot, due to old pack's deletion
> Updated content pack

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_crafting.lua
This avoids screwing with existing crafting recipes.
> Added 'return true' to CanCraft

- Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua
Disallow characters from transfering items from another character through storage (like for dropped items)
> Disallow characters from swapping items through storage

- Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_player.lua
player:Faction() doesn't exist, replaced it with player:GetFaction() instead.
> player:Faction() to player:GetFaction()

- upload/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua
Added a hook that gets called after the character initialized
> Added a hook that gets called after the character initialized and knockback hook

- upload/garrysmod/gamemodes/clockwork/framework/language/sh_korean.lua
> Fix wrong translation table.

- upload/garrysmod/gamemodes/clockwork/framework/cl_kernel.lua
restores sandbox functionality for weapons to change view model rendering angles and position
> allow weapons to manipulate viewmodels
