CloudSixteen/Clockwork

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/client/cl_fonts.lua

This allows fonts to load all UTF-8 characters, resulting in non-english text rendering with proper font.
Bright example of this is here: http://c2n.me/3yUlsb3.jpg
First line is som regular English text.
Second line is some Russian with extended = true.
Third one is some more Russian with extended = false or not set.

Force fonts to use extended character range

---

Clockwork/garrysmod/gamemodes/clockwork/plugins/animatedlegs/plugin/cl_plugin.lua

This was presumably broken by the latest GMod update. Clockwork.Client:GetObserverTarget() was returning a NULL Entity when the player wasn't spectating any entity.

Fixes issue where first-person legs don't show

---

Clockwork/garrysmod/gamemodes/clockwork/framework/meta/sv_player.lua

Fixed a typo in the GiveItems method that would try to give the table of item tables instead of the value of the for loop.

Fixed GiveItems

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua

Adding player:SetSharedVar("Flags", player:GetFlags()); to the end of both functions: 
function Clockwork:PlayerFlagsGiven(player, flags) & function Clockwork:PlayerFlagsTaken(player, flags)
This fixes the issue of flags not updating. Originally, the character would have to be reloaded to see updated flags. This fixes that.

Fixing Flags not updating - Fix to sv_kernel.lua

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua
Clockwork/garrysmod/gamemodes/clockwork/plugins/storage/plugin/sv_hooks.lua

Fixes Clockwork.kernel:IsShuttingDown so it doesn't always return nil.
Prevents container items from getting dropped while the server is shutting down.

Fix Clockwork.kernel:IsShuttingDown - Add Storage check

---

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_config.lua

Replaced dot with colon in the method definition to ensure "self" is defined.

Fixed undefined "self" within metamethod

---

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_crafting.lua

the 'CanCraft' callback method can now be used to create custom requirements for blueprints, expanding their functionality. Thanks RJ for the suggestion!

Added a new method to blueprints that enable custom requirements

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua

Catches an error thrown by the utf8sub method when it is passed invalid UTF8 data.
When string.utf8sub from the external library is called, it calls utf8.len from the GMod module, which in turn calls a local decoder function. Naturally, when it is passed data to decode which isn't UTF8 data, it returns nil. This causes utf8.len to send a boolean false as its first return, whereas valid UTF8 data being passed in as a parameter would cause a number to be returned. The unexpected boolean causes the error referenced in #435.
Ultimately, the error is caused by a lack of checking for invalid UTF8 data.

Caught error for invalid UTF8 data

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua

My recent UTF8 patch caused the file's content to be checked after its length is obtained. If the file does not exist and the content is nil, the length function errors, which differs from normal behaviour. This change corrects the issue.

Ensure file contents check before UTF8 length check

---

Clockwork/garrysmod/gamemodes/clockwork/framework/derma/cl_settings.lua

Currently tooltips aren't translated from their ID strings to their localised form within the settings menu, and this fixes that.
This can be seen by hovering your mouse over a UI element (like a checkbox or combobox) and observing the text that pops up.

Added localisation for settings tooltips

---

Clockwork/garrysmod/gamemodes/clockwork/plugins/displaytyping/plugin/sv_hooks.lua

In cases where a faction or rank typing sound is not specifically defined, Combine players typing will not trigger the default typing beep. This is because of `player.typingBeep = true` currently being set regardless of whether or not the sound is actually emitted in the `displaytyping` plugin. This value is checked by other hooks of the start typing event, thereby stopping them from running. To amend this, I've moved that assignment into the condition, so that it will only run if the sound runs as well.

Fixed lack of typing beep

---

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_plugin.lua

Sets the `PLUGIN` global back to whatever value it held before it was changed, rather than setting it to nil.
Other than resolving conflicts with any externals that may use this global, this will also permit a Clockwork plugin to include an "external" (not in `myPlugin/plugin/plugins/`) plugin or plugins directory without having its own `PLUGIN` table be overwritten in the process (using, say, `Clockwork.kernel.IncludePlugins`).

Added value restoration for the PLUGIN global

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua

Added rounding of the schema version read from the schema's descriptor file, due to imprecision in the obtained value.
The issue shows itself in the form of this startup message whilst running HL2RP v1.08:
```[Clockwork] Successfully loaded HL2 RP version 1.0799999237061 by kurozael.```
This is due to the fact that `util.KeyValuesToTable`, which is used to obtain schema information from the schema's descriptive .txt file, uses single precision floating point representation to store numbers. Given the fact that Lua 5.1 (and so GLua) uses double precision for its numbers, Lua performs pre-display rounding on the value under the assumption that it is a regular double precision value. To deal with this, we need to perform further rounding ourselves before storage to ensure that the version …

Added version rounding

---

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua

Ensures that text items displayed on the same line of the chatbox use the correct width value to determine where to start the display of text.
An example of the fault is shown in this image:
The text starts at the same place regardless of the multiplication of the text size, because it uses the same width value to determine its starting position regardless. The width value used is only correct when no text scaling is applied. This PR makes sure that the starting position of subsequent texts bases itself off of the actual width of the previous text, rather than the assumed width. As such, with this applied, chat text follows directly after the timestamp, with no overlap or gap.

Corrected multiplied chat text widths

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua

Currently, `Clockwork.kernel.ValidateTableKeys` performs value removal whilst the table is being iterated through. When the removal is performed, the values in the table with a higher integer index to the removed item will all shift down an index. The result is that the item which moved down into the removed item's index isn't checked. So, even if the value it holds is invalid, it will remain in `baseTable`.
This PR corrects this seemingly unintended behaviour.

Corrected ValidateTableKeys' value skipping

---

Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua

The `PlayerAdjustCharacterTable` hook is used by `PlayerDataStreamInfoSent` to check whether a character should be either added to the character menu, or deleted.
In order to ensure separation of duties for hooks, I have split the part of the hook which is used to adjust character data from the part which is used to make banning decisions.

Separated character adjustment from banning decisions

---

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_command.lua

The addition of commands to the directory's help listing at registration time without its removal causes hidden commands to appear in the directory.
I propose the removal of the addition code from the registration process, as it seems to serve no purpose given that `ClockworkDirectoryRebuilt` is called whenever the directory is built, which adds commands to the listing as needed.
This fixes #447.

Removes registration-time addition of commands to the directory listing. Fixes #447.

---

Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua
Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_command.lua
Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua

The localisation updates set command tips and texts to localisation IDs, without adding the mechanism to translate these strings. This PR adds display-time translation of the data.
The relevant areas seem to be the command library (for the notification if too few arguments are provided), the chatbox (for the visual hints when typing out a command), and the quickmenu library (for F1 option tooltips).
I state it as partial support because it doesn't provide support for the directory's command listing. Help entries are first created on command registration, which occurs before the client's language preference. The translation function depends on that convar if a language is not specified, causing an error if you want to translate the command help into the user's set language. So, I have left …

Localisation support for commands

---

upload/garrysmod/gamemodes/clockwork/framework/libraries/sh_animation.lua

instead of relying solely on .HoldType, which some weps do not have defined.

use both weapon.HoldType and weapon:GetHoldType()

---

upload/garrysmod/gamemodes/clockwork/framework/libraries/server/sv_storage.lua

Checks if the space system is enabled before checking if a container has reached the maximum space.
Fixes an issue where you couldn't give a storage more than 100 items while having the system disabled. Thanks, Aspect.

Check if the space system is enabled
